# Generated by Django 5.2.4 on 2025-07-31 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_towns_student_town'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buspass',
            name='qr_code_image',
        ),
    ]
