# Generated by Django 5.2.4 on 2025-08-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_buspass_qr_code_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buspass',
            unique_together={('student', 'month', 'year')},
        ),
    ]
