# Generated by Django 5.2.4 on 2025-08-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_buspass_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('clerk', 'Clerk')], default='student', max_length=10),
        ),
    ]
