# Generated by Django 5.2.4 on 2025-08-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='role',
        ),
    ]
