# Generated by Django 5.2.4 on 2025-08-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clerk'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_renewed_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_renewed_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
